### ISSUE TITLE
Dashed Lines

### ISSUE THREAD

**Issue by hozza** [linuxmint/mint-y-theme#1]
Hi Mint,

The Dark and Darker themes look much better when you change the 'outline-style: dashed;' in GTK 3 'gtk.css' to 'outline-style: none;'.

:+1:

**Comment by JosephMcc** [comment]
Maybe they look slightly cleaner without the focus lines enabled but...
We did this intentionally with Mint-X and it's been the source of complaints ever since. Removing those outlines makes the theme basically useless for navigating applications using the keyboard and I really don't want to do that. Removing basic functionality just to get a bit cleaner look is not a great idea in my opinion.
