### ISSUE TITLE
mint-y-dark could use more contrast

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/mint-y-theme#12]
I love the new mint-y-dark theme. Finally a dark theme out of the box. :+1: 

In light/sunny environments it's hard to see the differences though. Especially tabs, like terminal tabs. It could benefit from a bigger difference in shades, and do not be afraid to use darker dark. It looks awesome on OLED screens.

Example theme with more contrast, pretty much the only other realistic option: [vertex-theme](https://github.com/horst3180/vertex-theme#bug-reporting)

**Comment by Redsandro** [comment]
Also check out the _Quick Filter_ search field, this is not really working out:

![image](https://cloud.githubusercontent.com/assets/1702193/16013730/e5a1f134-318e-11e6-9456-3ca0ce00a411.png)

**Comment by JosephMcc** [comment]
Well it is supposed to be a flat style of theme. Vertex really isn't it's understandable that it features more contrast. It's just a design difference between the two themes. There is nothing stopping you from using another theme, it's one of the easiest things to modify in Mint.

I'll look into the synaptic thing. This is unfortunately one problem forever present in dark themes though. There are always little things that just aren't quite right and many them are unfixable.

**Comment by JosephMcc** [comment]
The issue with synaptic is fixed here: https://github.com/linuxmint/mint-y-theme/commit/7b476c75be74d295dd996bc931a842dcf84db634

The only real option was to use a light colored entry because of the way Synaptic applies that yellow color in it's code.

I'm going to close this since the synaptic issue is fixed. Style wise the current contrast matches well with what's used in the lighter versions of theme. Styling is highly subjective and I know not everyone is going to agree on the styling. Good thing there are a lot of choices out there.

**Comment by Redsandro** [comment]
@JosephMcc 
> Styling is highly subjective and I know not everyone is going to agree on the styling. Good thing there are a lot of choices out there.

For dark themes, there are actually no quality themes other than mint-y-dark and vertex-dark that seem to work properly in all aspects. So that's a negative on the lot of choices.

One could argue that there is a difference between pure style choices and usability choices. The latter one - for example, being able to distinguish between tabs - is not subjective, although there is a correlation.

The reason I brought up the perceived lack of contrast - which is leaning more towards an objective observation if you're working on a terrace with a coffee or bagel (although no coffee or bagel required to notice this) - is this text in the Mint 18 release notes:

> Themeing is a very important aspect of the operating system, because for your experience to be comfortable, your computer doesn't just need to work well, it also needs to make you feel at home.
>
> Mint-Y is a work in progress and __it will continue to change and to improve, with your feedback__, after the Linux Mint 18 release. 

With that in mind, I'm slightly disappointed that this contrast issue is disregarded rather than discussed. But I understand. People worked hard on this, and for their respective environments, it works.

**Comment by JosephMcc** [comment]
I'm sorry if you feel your feedback was ignored. That wasn't the intention. In some situations the lighter variations are likely a better solution. Like the ones you mention in bright lighting. My biggest argument against it is the idea of making a highly contrasted dark theme when it isn't that way in the light variation.

Also appreciate the bug report about synaptic. It would be nice to have separate issues for each problem though. That way when problems are solved issues can be closed instead of sitting open forever and eventually ignored.

**Comment by JosephMcc** [comment]
I apologize for closing/re-opening your issue on a regular basis :)

I created a new issue for design discussion here: https://github.com/linuxmint/mint-y-theme/issues/13 please feel free to contribute to that discussion.

**Comment by Redsandro** [comment]
Thank you. :)

I won't be queue'ing up issues within one issue anymore! :+1:
