### ISSUE TITLE
Dashed lines visible in file lists

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/mint-y-theme#14]
I'm not sure if this is on purpose or a bug. It looks odd to me so I'm opening an issue, but if not, please close this issue.

![image](https://cloud.githubusercontent.com/assets/1702193/16039321/653db8c0-3229-11e6-9418-15bf4d1c3530.png)

The dashed line is one pixel above and below the ending of the list:

![image](https://cloud.githubusercontent.com/assets/1702193/16039365/b7f22574-3229-11e6-9f19-8ef1277e9eb0.png)

OTOH, the ctrl+cursor non-selection is visible again with a dashed line and I missed that a lot in Mint-X, so big thumbs up for that! :+1:

**Comment by JosephMcc** [comment]
The dashed line is by design in Gtk3.18. It's meant to work in conjunction with the new overlay scrollbars as an indicator that there is more content when the scrollbars aren't visible. Not sure what desktop you use but in Cinnamon at least you can disable the overlay scrollbars in the settings. That doesn't however get rid of the dashed lines.

If you really want to hide them you can add a gtk.css file in ~/.config/gtk-3.0/ and add the following line:
`.undershoot.top, .undershoot.right, .undershoot.bottom, .undershoot.left { background-image: none; }`

They could possibly be themed a bit differently but from what I've seen the dashed lines are pretty much the standard that themes are using.

**Comment by Redsandro** [comment]
@JosephMcc ah, now that I understand what it is for, it makes sense. Thank you for clarifying. I'm using Cinnamon. I will probably disable the overlays and dashes until I upgrade to a laptop with touch screen.
