### ISSUE TITLE
Thunderbird drop down menus: unreadable on hover

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mint-y-theme#52]
Please see the almost totally unreadable white-on-grey in the image I attach.

![jfjdmgfcehgmnmoo](https://cloud.githubusercontent.com/assets/9998846/21700985/0c3beecc-d39b-11e6-99d5-ef489bb539c0.png)

I see that effect only when I have the Phoenity Shredder Thunderbird theme installed. Yet, the author of that theme tells me that his theme is not the problem and that, rather, the system theme is; and indeed, when I change my 'controls' theme from Mint-Y to something else, the problem disappears.

Mint 18.1 x64 Cinnamon.

**Comment by ghost** [comment]
This problem persist in Mint 18.3. The Mint-Y theme suffers from it, but the Mint-X themes, and, e.g. the 'Paper' theme (snwh.org/paper) does not. It's a real shame because the Phoenity Shredder Thunderbird theme is one of the best - and one the few unbroken - Thunderbird themes (or at least it's not broken unless one uses Mint-Y with it!).

**Comment by JosephMcc** [comment]
These are different in Mint19 and I don't think this issue is relevant anymore.
